# Generated by Django 3.2.7 on 2021-10-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baker', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
