# Generated by Django 3.2.7 on 2021-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baker', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num',
            field=models.CharField(max_length=100),
        ),
    ]
