# Generated by Django 3.2.7 on 2021-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baker', '0006_alter_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(max_length=100),
        ),
    ]
