# Generated by Django 3.2.7 on 2021-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baker', '0008_auto_20211004_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
